on:
  pull_request:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run Vite Size
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Calling vite-size script
        id: vite-size
        uses: glitch-txs/vite-size-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
